### ISSUE TITLE
Comparison to https://github.com/twop/ts-union

### ISSUE THREAD

**Issue by janwirth** [practical-fp/union-types#1]
Why should I use this project over that one: https://github.com/twop/ts-union

**Comment by felixschorer** [comment]
`ts-union` and many other similar libraries derive types from constructor functions. That works for most cases. However, once you run into recursive or generic union types, you will have to jump through a lot of hoops.

This project derives constructor functions from types by using [Proxies](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy). That solves all those issues.

If you don't need generic or recursive unions, pick whichever you think has the nicer API / more features.

**Comment by janwirth** [comment]
Thanks!
